name: flutter_install_app_plugin_example
description: Demonstrates how to use the flutter_install_app_plugin plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_install_app_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
