name: flutter_install_app_plugin_example
description: Demonstrates how to use the flutter_install_app_plugin plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_install_app_plugin:
    path: ../
  # flutter_web_plugins: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
